spring:
  application:
    name: innercircle

  datasource:
    url: jdbc:postgresql://localhost:5432/innercircle
    username: innercircle
    password: innercircle_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: innercircle-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.arjun.innercircle.*"

  graphql:
    graphiql:
      enabled: true # browser playground at /graphiql
    websocket:
      path: /graphql-ws

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

server:
  port: 8080

innercircle:
  kafka:
    topics:
      chat-messages: chat-messages
  invite-key:
    length: 6
